apiVersion: v1
kind: ConfigMap
metadata:
  name: xroad-config
data:
  instance-identifier: |
    TG
  local.ini: |
    ; This file contains user overrides of properties
    ; Add all configuration options with sections from each configuration unit
  local.properties: |
    ; This file contains user overrides of properties
  db.properties: |
    serverconf.hibernate.connection.url=jdbc:postgresql://postgres.default.svc:5432/serverconf
    serverconf.hibernate.connection.username=root
    serverconf.hibernate.connection.password=rootpassword
    op-monitor.hibernate.connection.url=jdbc:postgresql://postgres.default.svc:5432/op-monitor
    op-monitor.hibernate.connection.username=root
    op-monitor.hibernate.connection.password=rootpassword
    messagelog.hibernate.connection.url=jdbc:postgresql://postgres.default.svc:5432/messagelog
    messagelog.hibernate.connection.username=root
    messagelog.hibernate.connection.password=rootpassword
  xroad.properties: |
    postgres.connection.user = root
    postgres.connection.password = rootpassword
  variables-logback.properties: |
    XROAD_LOG_LEVEL=INFO
    XROAD_ROOT_LOG_LEVEL=WARN
  devices.ini: |
    ; This configuration file defines the available Secure Signature
    ; Creation Devices (SSCD).
  ssl.properties: |
    server.ssl.enabled=false
    server.ssl.key-store-type=PKCS12
    server.ssl.key-store-password=password
    server.ssl.key-alias=1
  configuration-anchor.xml: |