apiVersion: apps/v1
kind: Deployment
metadata:
    name: x-road-catalog-collector
    labels:
        app: x-road-catalog-collector
spec:
    replicas: 3
    selector:
        matchLabels:
            app: x-road-catalog-collector
    template:
        metadata:
            labels:
                app: x-road-catalog-collector
        spec:
            containers:
                - name: x-road-catalog-collector
                  image: nordic-institute/x-road-catalog-collector:latest
                  ports:
                      - containerPort: 8080
